language: c
dist: trusty   # Travis build machine is Ubuntu Trusty 14.04 x64
sudo: required # A sudo enabled, full VM is used for building instead of a docker container

before_install:
  - sudo apt-get update -qq
  # Pre-reqs for building omsagent and omi
  - sudo apt-get install -qq pkg-config make ruby bison g++ rpm librpm-dev libpam0g-dev libssl-dev libmysqlclient-dev libkrb5-dev
  # Pre-reqs for building auoms
  - sudo apt-get install cmake libboost-dev libboost-test-dev libaudit-dev libauparse-dev unzip
  - sudo groupadd omiusers
  - rvm use system                 # Use system ruby (v1.9.3p484) instead of ruby provided by rvm
  - sed -i 's/--no-ri//' ~/.gemrc  # ri data from installed gems is required for our build

# Travis-CI automatically clones the OMS-Agent-for-Linux repo since this is where this .travis.yml file is located
# We will ignore this clone and clone the superproject Build-OMS-Agent-for-Linux as follows

install:
  - cd ../..
  - git config --global 'url.https://github.com/.insteadOf' 'git@github.com:'
  - git clone --recursive https://github.com/Microsoft/Build-OMS-Agent-for-Linux.git Microsoft/Build-OMS-Agent-for-Linux

before_script:
  - cd Microsoft/Build-OMS-Agent-for-Linux 
  - git checkout master && git submodule foreach git checkout master
  - rm -rf omsagent
  - cp ../OMS-Agent-for-Linux omsagent
  - cd omsagent/build 
  # pwd: /home/travis/build/Microsoft/Build-OMS-Agent-for-Linux/omsagent/build
  # Since 'build' is a keyword for travis-CI, change Makefile to substitute 'omsagent/build' instead of 'build'
  - sed -i 's/(subst \/build,,$(CURDIR))/(subst omsagent\/build,omsagent,$(CURDIR))/' Makefile 
  # Substitue 'build' in Makefile for auoms as well
  - sed -i 's/(subst \/build,,$(CURDIR))/(subst auoms\/build,auoms,$(CURDIR))/' ../../auoms/build/Makefile

script:
  - ./configure --enable-debug
  - make && make unittest # System tests are not run because OMS-Agent-for-Linux-testconfig.git is a private repo
